IRKIT_ADDRESS: 
IRKIT_DATA_DIR:
IRKIT_CLIENTKEY: YOUR_IRKIT_CLIENTKEY
IRKIT_DEVICEID: YOUR_IRKIT_DEVICEID
DEVICE_NAME: myhouse
AWS_ACCESS_KEY_ID: YOUR_DYNAMO_ACCESS_ID
AWS_SECRET_ACCESS_KEY: YOUR_DYNAMO_SECRET_ACCESS_KEY
AWS_REGION: ap-northeast-1
